apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-entry

spec:
  type: NodePort
  ports:
    - targetPort: web
      name: web
      port: 80
    - targetPort: websecure
      name: websecure
      port: 443
  selector:
    app: traefik
---
