apiVersion: v1
kind: Service
metadata:
  name: traefik-public

spec:
  type: LoadBalancer
  ports:
    - targetPort: websecure
      name: websecure-public
      port: 443
  selector:
    app: traefik
