apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: le-http

spec:
 acme:
   email: bl@ise.ninja
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: homework-key
   solvers:
     - http01:
         ingress:
           class: traefik
