kind: Deployment
apiVersion: apps/v1
metadata:
  name: homework-server
  labels:
    app: homework-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: homework-server
  template:
    metadata:
      labels:
        app: homework-server
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
        - name: redis
            image: redis
            ports:
              - name: redis
                containerPort: 6379