apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homework-ingress

spec:
  tls:
    - hosts:
      - hw.ise.international
      secretName: tls-homework-ingress-http
  rules:
  - host: hw.ise.international
    http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homework-service
              port:
                name: web
